CREATE DATABASE IF NOT EXISTS tourist_DB DEFAULT CHARACTER SET utf8;
USE tourist_DB;

CREATE TABLE TOURISTATTRACTION (
	ATTRACTIONNO INTEGER, 
	ATTRACTIONNAME VARCHAR(30), 
	LOC VARCHAR(30), 
    ATTRACTIONDESC VARCHAR(100),
	PRIMARY KEY (ATTRACTIONNO)
);

