CREATE DATABASE IF NOT EXISTS tourist_DB DEFAULT CHARACTER SET utf8;
USE tourist_DB;

DROP TABLE IF EXISTS TOURISTATTRACTION;

CREATE TABLE TOURISTATTRACTION (
	ATTRACTIONNO INTEGER, 
	ATTRACTIONNAME VARCHAR(30), 
	ATTRACTIONDISTRICT VARCHAR(30), 
    ATTRACTIONCITY VARCHAR(30),
    ATTRACTIONDESC VARCHAR(100),
    ATTRACTIONTAGS VARCHAR (30),
	PRIMARY KEY (ATTRACTIONNO)
);

