CREATE DATABASE IF NOT EXISTS tourist_DB DEFAULT CHARACTER SET utf8;
USE tourist_DB;

DROP TABLE IF EXISTS TOURISTATTRACTION;

CREATE TABLE TOURISTATTRACTION (
	ATTRACTIONNO INTEGER AUTO_INCREMENT, 
	ATTRACTIONNAME VARCHAR(30),
	ATTRACTIONDISTRICT VARCHAR(30), 
    ATTRACTIONCITY VARCHAR(30),
    ATTRACTIONDESC VARCHAR(100),
    ATTRACTIONTAGS VARCHAR (30),
	PRIMARY KEY (ATTRACTIONNO)
);

INSERT INTO TOURISTATTRACTION (ATTRACTIONNAME, ATTRACTIONDISTRICT, ATTRACTIONCITY, ATTRACTIONDESC, ATTRACTIONTAGS)
VALUES ('Test Attraction', 'Test District', 'Test City', 'This is a test description.', 'test,example');

SELECT * FROM TOURISTATTRACTION;